services:
  homeseer:
    container_name: homeseer
    image: spudwebb/homeseer:latest
    hostname: homeseer
    restart: unless-stopped
    network_mode: bridge
    volumes:
      - /usr/local/homeseer:/homeseer
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 80:80
      - 1883:1883
      - 10200:10200
      - 10300:10300
      - 10401:10401
      - 11000:11000
    environment:
      TZ: America/New_York
      LANG: en_US.UTF-8
      DOCKER_HOMESEER_HOST_ROOT: "/usr/local/homeseer"

